### ISSUE TITLE
Safe operators stop before unmatched apostrophe in elisp comments when using smartparens-config

### ISSUE THREAD

**Issue by braham-snyder** [expez/evil-smartparens#38]
With `smartparens-strict-mode` and `(require 'smartparens-config)`, safe operators can behave incorrectly on unmatched apostrophes in emacs lisp comments. For example, `dd` (with point anywhere) on the following line:
```
;; doesn't that
```
leaves:
```
't that
```
Seems to be caused by the \`' pair, [here](https://github.com/Fuco1/smartparens/blob/master/smartparens-config.el#L72) in `smartparens-config`:
```
(sp-with-modes (-difference sp-lisp-modes sp-clojure-modes)
  ;; also only use the pseudo-quote inside strings where it serve as
  ;; hyperlink.
  (sp-local-pair "`" "'"
                 :when '(sp-in-string-p
                         sp-in-comment-p)
                 :unless '(sp-lisp-invalid-hyperlink-p)
                 :skip-match (lambda (ms mb me)
                               (cond
                                ((equal ms "'")
                                 (or (sp-lisp-invalid-hyperlink-p "`" 'navigate '_)
                                     (not (sp-point-in-string-or-comment))))
                                (t (not (sp-point-in-string-or-comment)))))))
```

**Comment by expez** [comment]
Use `evil-sp-override`, bound to <kbd>o</kbd> in visual-state, to get around this edge-case.  

If you want to pursue this further, the issue belongs over in the smartparens repo.

**Comment by expez** [comment]
Let me add a bit more details.  The problem happens because `'` is the closing half of a pair, so when this token appears on its own smartparens says 'this region is unbalanced' and evil-smartparens shrinks the region in an attempt at DWIM.

How can we differentiate between a failed pair insertion and the use of `'` in text?  We would have to do semantic analysis to find out the **meaning** behind the text.  Nevermind that this is hard, but it would also be so costly to do that it would leave the package unusable for the general case.

This is why I said this was an 'edge case', that we probably shouldn't invest much time in.

**Comment by braham-snyder** [comment]
fair enough--it just wasn't clear to me what your stance on this was since I didn't see it documented anywhere
